create table
  public.book_authors (
    id bigint generated by default as identity not null,
    name text not null default ''::text,
    link text null default ''::text,
    image text null default ''::text,
    born text null default ''::text,
    web text null default ''::text,
    bio text null default ''::text,
    created_at timestamp with time zone null default now(),
    constraint book_authors_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.book_books (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    author_id bigint null,
    title text not null default ''::text,
    isbn text null default ''::text,
    language text null default ''::text,
    pages text null default ''::text,
    published date null,
    genre text null default ''::text,
    rating text null default ''::text,
    score text null default ''::text,
    vote text null default ''::text,
    link text null default ''::text,
    image text null default ''::text,
    image_small text null default ''::text,
    description text null default ''::text,
    constraint book_books_pkey primary key (id),
    constraint book_books_author_id_fkey foreign key (author_id) references book_authors (id)
  ) tablespace pg_default;

create table
  public.book_books_genres (
    id bigint generated by default as identity not null,
    book_id bigint null,
    genre_id bigint null,
    created_at timestamp with time zone null default now(),
    constraint book_books_genres_pkey primary key (id),
    constraint book_books_genres_book_id_fkey foreign key (book_id) references book_books (id),
    constraint book_books_genres_genre_id_fkey foreign key (genre_id) references book_genres (id)
  ) tablespace pg_default;

create table
  public.book_genres (
    id bigint generated by default as identity not null,
    name text not null default ''::text,
    link text null default ''::text,
    created_at timestamp with time zone null default now(),
    constraint book_genres_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.book_logs (
    id bigint generated by default as identity not null,
    user_id bigint null,
    action text null default ''::text,
    table text null default ''::text,
    description text null default ''::text,
    created_at timestamp with time zone null default now(),
    constraint book_logs_pkey primary key (id),
    constraint book_logs_user_id_fkey foreign key (user_id) references book_users (id)
  ) tablespace pg_default;

create table
  public.book_sessions (
    id bigint generated by default as identity not null,
    user_id bigint null,
    token text null,
    created_at timestamp with time zone null default now(),
    constraint book_sessions_pkey primary key (id),
    constraint book_sessions_user_id_fkey foreign key (user_id) references book_users (id)
  ) tablespace pg_default;

create table
  public.book_users (
    id bigint generated by default as identity not null,
    name text null,
    username text null,
    password text null,
    type text null,
    created_at timestamp with time zone null default now(),
    constraint book_users_pkey primary key (id)
  ) tablespace pg_default;