create table
  public.vacation_category (
    id bigint generated by default as identity,
    name text null,
    created_at timestamp with time zone not null default now(),
    image_url text null,
    slug text null,
    constraint vacation_category_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.vacation_destination (
    id bigint generated by default as identity,
    name text null,
    image_url text null,
    description text null,
    video_url text null,
    island_id bigint null,
    province_id bigint null,
    created_at timestamp with time zone not null default now(),
    location text null,
    slug text null,
    content text null,
    header_image_url text null,
    url text null,
    constraint vacation_destination_pkey primary key (id),
    constraint vacation_destination_island_id_fkey foreign key (island_id) references vacation_island (id),
    constraint vacation_destination_province_id_fkey foreign key (province_id) references vacation_province (id)
  ) tablespace pg_default;

create table
  public.vacation_destination_category (
    id bigint generated by default as identity,
    destination_id bigint null,
    category_id bigint null,
    created_at timestamp with time zone not null default now(),
    constraint vacation_destination_category_pkey primary key (id),
    constraint vacation_destination_category_category_id_fkey foreign key (category_id) references vacation_category (id),
    constraint vacation_destination_category_destination_id_fkey foreign key (destination_id) references vacation_destination (id)
  ) tablespace pg_default;

create table
  public.vacation_island (
    id bigint generated by default as identity,
    name text null,
    image_url text null,
    created_at timestamp with time zone not null default now(),
    slug text null,
    constraint vacation_island_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.vacation_log (
    id bigint generated by default as identity,
    user_id bigint null,
    action text null,
    "table" text null,
    description text null,
    created_at timestamp with time zone not null default now(),
    constraint vacation_log_pkey primary key (id),
    constraint vacation_log_user_id_fkey foreign key (user_id) references vacation_user (id)
  ) tablespace pg_default;

create table
  public.vacation_province (
    id bigint generated by default as identity,
    name text null,
    image_url text null,
    created_at timestamp with time zone not null default now(),
    island_id bigint null,
    slug text null,
    constraint vacation_province_pkey primary key (id),
    constraint vacation_province_island_id_fkey foreign key (island_id) references vacation_island (id)
  ) tablespace pg_default;

create table
  public.vacation_session (
    id bigint generated by default as identity,
    user_id bigint null,
    token text null,
    created_at timestamp with time zone not null default now(),
    constraint vacation_session_pkey primary key (id),
    constraint vacation_session_user_id_fkey foreign key (user_id) references vacation_user (id)
  ) tablespace pg_default;

create table
  public.vacation_user (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    username text null,
    name text null,
    type text null,
    password text null,
    constraint vacation_user_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.vacation_video (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    title text null,
    video_url text null,
    island_id bigint null,
    province_id bigint null,
    constraint vacation_video_pkey primary key (id),
    constraint vacation_video_island_id_fkey foreign key (island_id) references vacation_island (id),
    constraint vacation_video_province_id_fkey foreign key (province_id) references vacation_province (id)
  ) tablespace pg_default;